### ISSUE TITLE
Share list to group: the voteCount is not intialized

### ISSUE THREAD

**Issue by AaronHongyangLiu** [TeamGhostBuster/restful-api#38]
after a list is shared to a group, the vote count for the articles is DoesNoteExist

**Comment by ExiaSR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix shared list in group](https://trello.com/c/fxj0VgO4/21-fix-shared-list-in-group)

**Comment by ExiaSR** [comment]
Fix with Pull Request #40
